name: deploy-github-packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to publish v[0-9]+.[0-9]+.[0-9]+*'
        required: true
        default: ''
        type: string
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  get-version:
    name: Get version to deploy
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0
    outputs:
      VERSION: ${{ steps.output-version.outputs.VERSION }}
    steps:
    - name: Set tag from input
      if: ${{ github.event.inputs.version != '' }}
      env:
        TAG: ${{ github.event.inputs.version }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Set version variable from tag
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: VERSION to job output
      id: output-version
      run: |
        echo "VERSION=${{ env.VERSION }}" >> $GITHUB_OUTPUT

  deploy-github:
    name: Deploy nuget package to GitHub packages
    needs: get-version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'refs/tags/v${{ needs.get-version.outputs.VERSION }}'

    - name: Setup .NET
      uses: ./.github/setup-dotnet
      with:
        dotnet-version: 8.0.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.TOKEN }}

    - name: Build the package(s)
      run: dotnet build -c Release

    - name: Create the package(s)
      run: dotnet pack -c Release /p:PackageVersion=${{ needs.get-version.outputs.VERSION }} /p:AssemblyVersion=${{ needs.get-version.outputs.VERSION }} /p:Version=${{ needs.get-version.outputs.VERSION }}

    - name: Publish nuget package
      run: dotnet nuget push */bin/Release/*.nupkg --skip-duplicate

    - name: Push nuget generated package symbols
      run: dotnet nuget push */bin/Release/*.snupkg --skip-duplicate
